version: "3"

services:
  wbanode1:
    container_name: wbanode1
    image: "wba-chain:latest"
    # build: .
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-wbad.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26657:26657"
      - "26656:26656"      
      - "1317:1317"
      - "9090:9090"
      - "8080:8080"
    volumes:      
      - ./docker/.testnets/v1:/root/.wbad/:rw      
    command: wbad start --home /root/.wbad/ --moniker wbanode1 --p2p.persistent_peers "97c243ce12df828f9e321f33dc36d2639a912913@wbanode2:26666"
    networks:
      localnet:
        ipv4_address: 192.168.12.2

  wbanode2:
    container_name: wbanode2
    image: "wba-chain:latest"
    # build: .
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-wba.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26667:26667"
      - "26666:26666"
      - "1327:1317"
      - "9101:9101"
      - "9100:9100"        
    volumes:      
      - ./docker/.testnets/v2:/root/.wbad/:rw 
    command: wbad start --home /root/.wbad/ --moniker wbanode2 --address "tcp://wbanode2:26668" --grpc-web.address "wbanode2:9101" --grpc.address "wbanode2:9100" --p2p.laddr "tcp://wbanode2:26666" --rpc.laddr "tcp://wbanode2:26667" --proxy_app "tcp://wbanode2:26668" --p2p.persistent_peers "bc81ba1eaae5cb4f80e1d18fa0a5e79e99488ffd@wbanode1:26656" # --api.address "tcp://0.0.0.0:1327"
    # command: ls /root/.wbad/config
    networks:
      localnet:
        ipv4_address: 192.168.12.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.12.0/25
          gateway: 192.168.12.1